# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip, fetchgit }:

linkFarm "zig-packages" [
  {
    name = "zig_objc-0.0.0-Ir_Sp7oUAQC3JpeR9EGUFGcHRSx_33IehitnjBCy-CwD";
    path = fetchzip {
      url = "https://codeload.github.com/mitchellh/zig-objc/tar.gz/refs/heads/main";
      hash = "sha256-+twiDWxrDpGAaFHJvf5tv90f4mXgAyHbgNjTyzu7d9s=";
    };
  }
]
